### ISSUE TITLE
code doesn't work

### ISSUE THREAD

**Issue by LinhGit** [bilibilifmk/ESP_Fishing#2]
Hi, I am very much inspired by your project.
but when using this source code for arduino ide compiler it doesn't work. when logging in 6.6.6.6 nothing happens. can you fix the error.

**Comment by bilibilifmk** [comment]
https://github.com/esp8266/arduino-esp8266fs-plugin/releases  You need to use this to upload to the FS

**Comment by LinhGit** [comment]
Thanks for replies !

Vào Th 7, 13 thg 11, 2021 vào lúc 12:41 发明控 ***@***.***> đã
viết:
