### ISSUE TITLE
编译项目时卡住，最后报错

### ISSUE THREAD

**Issue by zhu956645239** [bilibilifmk/ESP_Fishing#3]
![image](https://user-images.githubusercontent.com/38211259/142729539-3d285d7d-6584-438a-aca6-9f14d3cebee1.png)

Arduino:1.8.9 (Windows 10), 开发板："Generic ESP8266 Module, 80 MHz, Flash, Disabled, All SSL ciphers (most compatible), ck, 26 MHz, 40MHz, DOUT (compatible), 4M (1M SPIFFS), 2, nonos-sdk 2.2.1 (legacy), v2 Lower Memory, Disabled, None, Only Sketch, 115200

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:22:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:24:13: error: redefinition of 'const char* AP_name'

 const char *AP_name = "wifi_link_tool";

             ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:1:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:24:13: error: 'const char* AP_name' previously defined here

 const char *AP_name = "wifi_link_tool";

             ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:22:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:28:8: error: redefinition of 'String Version'

 String Version ="1.0.0";

        ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:1:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:28:8: error: 'String Version' previously declared here

 String Version ="1.0.0";

        ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:22:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:29:8: error: redefinition of 'String Hostname'

 String Hostname = "ESP8266";

        ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:1:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:29:8: error: 'String Hostname' previously declared here

 String Hostname = "ESP8266";

        ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:22:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:30:5: error: redefinition of 'int Signal_filtering'

 int Signal_filtering = -200;

     ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:1:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:30:5: error: 'int Signal_filtering' previously defined here

 int Signal_filtering = -200;

     ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:22:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:31:12: error: redefinition of 'const byte DNS_PORT'

 const byte DNS_PORT = 53;

            ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:1:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:31:12: error: 'const byte DNS_PORT' previously defined here

 const byte DNS_PORT = 53;

            ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:22:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:32:5: error: redefinition of 'int WiFi_State'

 int WiFi_State;

     ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:1:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:32:5: error: 'int WiFi_State' previously declared here

 int WiFi_State;

     ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:22:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:34:6: error: redefinition of 'bool wxscan'

 bool wxscan=true;

      ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:1:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:34:6: error: 'bool wxscan' previously defined here

 bool wxscan=true;

      ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:22:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:35:5: error: redefinition of 'int rstb'

 int rstb=0;

     ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:1:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:35:5: error: 'int rstb' previously defined here

 int rstb=0;

     ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:22:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:36:5: error: redefinition of 'int stateled'

 int stateled=2;

     ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:1:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:36:5: error: 'int stateled' previously defined here

 int stateled=2;

     ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:22:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:37:15: error: redefinition of 'IPAddress apIP'

 IPAddress apIP(6, 6, 6, 6);

               ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:1:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:37:11: error: 'IPAddress apIP' previously declared here

 IPAddress apIP(6, 6, 6, 6);

           ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:22:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:38:11: error: redefinition of 'DNSServer dnsServer'

 DNSServer dnsServer;

           ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:1:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:38:11: error: 'DNSServer dnsServer' previously declared here

 DNSServer dnsServer;

           ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:22:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:39:27: error: redefinition of 'ESP8266WebServer webServer'

 ESP8266WebServer webServer(80);

                           ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:1:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:39:18: error: 'ESP8266WebServer webServer' previously declared here

 ESP8266WebServer webServer(80);

                  ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:22:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h: In function 'void info()':

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:58:6: error: redefinition of 'void info()'

 void info(){

      ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:1:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:58:6: error: 'void info()' previously defined here

 void info(){

      ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:22:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h: In function 'void pant()':

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:69:6: error: redefinition of 'void pant()'

 void pant() {

      ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:1:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:69:6: error: 'void pant()' previously defined here

 void pant() {

      ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:22:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h: In function 'void torest()':

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:74:6: error: redefinition of 'void torest()'

 void torest() {

      ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:1:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:74:6: error: 'void torest()' previously defined here

 void torest() {

      ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:22:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h: In function 'int link()':

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:83:5: error: redefinition of 'int link()'

 int link() {

     ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:1:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:83:5: error: 'int link()' previously defined here

 int link() {

     ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:22:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h: At global scope:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:91:23: error: redefinition of 'char data_buffer [6000]'

 char data_buffer[buf_s];

                       ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:1:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:91:6: error: 'char data_buffer [6000]' previously declared here

 char data_buffer[buf_s];

      ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:22:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:92:5: error: redefinition of 'int bufwz'

 int bufwz = 0;

     ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:1:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:92:5: error: 'int bufwz' previously defined here

 int bufwz = 0;

     ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:22:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h: In function 'void sendBuffer()':

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:93:6: error: redefinition of 'void sendBuffer()'

 void sendBuffer() {

      ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:1:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:93:6: error: 'void sendBuffer()' previously defined here

 void sendBuffer() {

      ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:22:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h: In function 'void sendToBuffer(String)':

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:99:6: error: redefinition of 'void sendToBuffer(String)'

 void sendToBuffer(String str) {

      ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:1:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:99:6: error: 'void sendToBuffer(String)' previously defined here

 void sendToBuffer(String str) {

      ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:22:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h: In function 'void sendHeader(int, String, size_t)':

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:108:6: error: redefinition of 'void sendHeader(int, String, size_t)'

 void sendHeader(int code, String type, size_t _size) {

      ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:1:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:108:6: error: 'void sendHeader(int, String, size_t)' previously defined here

 void sendHeader(int code, String type, size_t _size) {

      ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:22:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h: In function 'void wifi_link_tool_hex(int, String, const char*, size_t)':

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:112:7: error: redefinition of 'void wifi_link_tool_hex(int, String, const char*, size_t)'

 void  wifi_link_tool_hex(int code, String type, const char* adr, size_t len) {

       ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:1:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:112:7: error: 'void wifi_link_tool_hex(int, String, const char*, size_t)' previously defined here

 void  wifi_link_tool_hex(int code, String type, const char* adr, size_t len) {

       ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:22:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h: In function 'void wwwroot()':

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:117:6: error: redefinition of 'void wwwroot()'

 void wwwroot() {

      ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:1:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:117:6: error: 'void wwwroot()' previously defined here

 void wwwroot() {

      ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:22:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h: In function 'void wifiConfig()':

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:140:6: error: redefinition of 'void wifiConfig()'

 void wifiConfig() {

      ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:1:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:140:6: error: 'void wifiConfig()' previously defined here

 void wifiConfig() {

      ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:22:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h: In function 'String wifi_type(int)':

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:197:8: error: redefinition of 'String wifi_type(int)'

 String wifi_type(int typecode) {

        ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:1:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:197:8: error: 'String wifi_type(int)' previously defined here

 String wifi_type(int typecode) {

        ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:22:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h: In function 'void wifiScan()':

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:204:6: error: redefinition of 'void wifiScan()'

 void wifiScan() {

      ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:1:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:204:6: error: 'void wifiScan()' previously defined here

 void wifiScan() {

      ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:22:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h: In function 'void opera()':

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:231:6: error: redefinition of 'void opera()'

 void opera() {

      ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:1:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:231:6: error: 'void opera()' previously defined here

 void opera() {

      ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:22:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h: In function 'String gethttp_API(String, int)':

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:261:8: error: redefinition of 'String gethttp_API(String, int)'

 String gethttp_API(String url,int port){

        ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:1:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:261:8: error: 'String gethttp_API(String, int)' previously defined here

 String gethttp_API(String url,int port){

        ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:22:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h: In function 'void ota()':

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:273:6: error: redefinition of 'void ota()'

 void ota(){

      ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:1:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:273:6: error: 'void ota()' previously defined here

 void ota(){

      ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:22:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h: In function 'void blink()':

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:303:6: error: redefinition of 'void blink()'

 void blink() {

      ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:1:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:303:6: error: 'void blink()' previously defined here

 void blink() {

      ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:22:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h: In function 'void load()':

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:337:6: error: redefinition of 'void load()'

 void load() {

      ^

In file included from C:\Users\Administrator\Documents\Arduino\ESP_Fishing-main\ESP_Fishing\ESP_Fishing.ino:1:0:

C:\Users\Administrator\Documents\Arduino\libraries\wifi_link_tool-master/wifi_link_tool.h:337:6: error: 'void load()' previously defined here

 void load() {

      ^

exit status 1
为开发板 Generic ESP8266 Module 编译时出错。

在文件 -> 首选项开启
“编译过程中显示详细输出”选项
这份报告会包含更多信息。

**Comment by zuikaola** [comment]
把最上面两行代码删除，其实上传也没有用，没有魔改的SDK，刷了也没有用，没有攻击能力，不会把客户端踢下来，所以还需要SDK，SDK没有公布，所以基本没有啥用。

**Comment by bilibilifmk** [comment]
那个sdk 上传到 qq群了 不过好像没了 我会重新上传 我不知道你改了什么 好像是 hex无法解析

**Comment by 1102196883** [comment]
> 

QQ群在哪啊?
我进去怎么是老色皮群，呜呜呜
